### ISSUE TITLE
Bits call method

### ISSUE THREAD

**Issue by JakeStevens** [cornell-brg/pymtl3#149]
Is there a particular reason why the __call__ method is overwritten for the Bits datatype, as in:

```
def __call__( self ):
   return Bits( self.nbits )
```

It does not seem intuitive to me that calling an **instance** of a Bits object should provide another Bits object with the same number of bits, but equal to zero.

**Comment by jsn1993** [comment]
oh, I think this code hasn't been touched for a while and I forgot why I wrote that lol. I don't think we actually use `__call__ ` in practice. I can remove that.

**Comment by JakeStevens** [comment]
If there is no specific, reason, I think that may be good to remove; it can lead to confusing bugs if you're not expecting it
