### ISSUE TITLE
Add a backdoor flag to disable verilator/c++ optimizations flags to make travis run faster

### ISSUE THREAD

**Issue by jsn1993** [cornell-brg/pymtl3#69]
For example, one way to do In travis we set a backdoor flag in environment, in your pass you check if there is a flag. If so we disable some optimizations to make compilation faster. This can speed up travis runs.

However, if we will run some long simulation in pymtl repo in travis. If so, we might want to spend the compilation overhead to speed up simulation.

**Comment by ptpan** [comment]
Closing because we want CI to capture the bugs
