### ISSUE TITLE
Better names for translated components with parameters

### ISSUE THREAD

**Issue by ptpan** [cornell-brg/pymtl3#75]
The current PyMTL translation pass generates a pretty long name that includes the names and values of parameters. This naming scheme becomes awkward when a component has several parameters and when these parameters have long names. We even experienced verilator compilation error when the translated name of some component grows too long (> 100 characters?). Also there are situations where customized component names are useful (e.g. integrating PyMTL generated designs with larger projects where we want to swap in PyMTL generated components without changing the external design code; also in our ASIC flow scripts it would be nice to use the same name for the top component).

We need (1) a way to make component names shorter (hashing?) and (2) to provide support for customized component names (a mapping between parameters and name?).

**Comment by jsn1993** [comment]
Can we close this since #93 is already merged?

**Comment by ptpan** [comment]
> Can we close this since #93 is already merged? @ptpan

The (2) part is still not done yet

**Comment by jsn1993** [comment]
@ptpan is this done by our new placeholder/translate/import pass?
