### ISSUE TITLE
Add translation support for SystemVerilog `enum` data type

### ISSUE THREAD

**Issue by ptpan** [cornell-brg/pymtl3#83]
The current PyMTL 3 behavioral modeling does not support `MsgType.MEM_AMO` syntax if `MsgType` is a Python class or an instance of a Python class. The translation pass does not know the hardware correspondent of `MsgType` and chooses to abort the translation.

It would be nice to support the above syntax and translate it to SystemVerilog `enum` data type.

**Comment by jsn1993** [comment]
@ptpan do you think your constant inference can cover the enum issue?

**Comment by ptpan** [comment]
Closing as #164 has been merged into master
