### ISSUE TITLE
Back-port dynamic index feature to SystemVerilog backend

### ISSUE THREAD

**Issue by ptpan** [cornell-brg/pymtl3#97]
The current yosys backend supports indexing into an array with signals or loop variables (i.e. the "dynamic" values). This feature is orthogonal to the choice of backend and should be back-ported to SystemVerilog backend, which will be our most-used backend that drives ASIC/FPGA flows.

**Comment by jsn1993** [comment]
@ptpan i guess this has been implemented in the dev branch?

**Comment by ptpan** [comment]
Closing as #158 has been merged into master
