### ISSUE TITLE
How can it get .tf file?

### ISSUE THREAD

**Issue by ehdans06** [cornell-brg/pymtl3#99]
Hello.
I'm now trying to use pymtl3, but the script incurs ".tf file except error."
I think the source code does not have .tf file. (even though other FreePDK files exist )
How can I circumvent this issue?

Thanks.

**Comment by cbatten** [comment]
Can you explain more what you are trying to do? Maybe you can provide step by step instructions explaining what you are trying and where the error occurs.

**Comment by cbatten** [comment]
I am going to close this but feel free to reopen if you want to add some more context ...
